---
deployment:
  tasks:
    - export DEPLOYPATH=/home/xl3al9825mkr/public_html/
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp output.css $DEPLOYPATH
    - /bin/cp index.7984e6eb.js $DEPLOYPATH
    - /bin/cp -R images $DEPLOYPATH